### ISSUE TITLE
RIDE can't recognize SwingLibrary

### ISSUE THREAD

**Issue by fli008** [robotframework/SwingLibrary#101]
When I import SwingLibrary in RIDE, but RIDE cannot recognize SwingLibrary. Could anyone help on this issue?
![swing](https://user-images.githubusercontent.com/35214708/34661872-7bac21ba-f487-11e7-800f-a866748ab30a.png)
I installed JDK 1.8, pybot 2.7.13, jybot 2.7.13, and also RIDE 3.0.2 successfully.
I need to test swinglibrary, then I download swinglibrary-1.9.7.jar and put it under C:\jython2.7.0 which had been put in system path.but RIDE cannot recognize SwingLibrary.
![environment](https://user-images.githubusercontent.com/35214708/34661870-77573cc6-f487-11e7-8b9f-7b2cfadbcef8.png)

**Comment by HelioGuilherme66** [comment]
@fli008 This is RIDE question that it is answered here at [RIDE's WIKI](https://github.com/robotframework/RIDE/wiki/Keyword-Completion#libraries-not-available-locally-or-written-in-java)
Please close this issue since is not related to SwingLibrary and because is a question, which should be preferably done on other channels, like Google Groups or Slack .

**Comment by fli008** [comment]
Thanks very much for your timely support!
I struggled yesterday and last night, still can't fix it. 

Anyway, since it is a RIDE issue, so I will close this issue firstly and then continue to study the RIDE's WIKI.

thanks!
Frank

**Comment by HelioGuilherme66** [comment]
@fli008 You should get the file SwingLibrary-1.9.7.xml from [Releases](https://github.com/robotframework/SwingLibrary/releases/tag/1.9.7) and install it where RIDE will find it. You could follow the instructions from the "Import Failed Help" button on RIDE (In the Settings section where you see the red SwingLibrary).
