### ISSUE TITLE
how to select table by class name

### ISSUE THREAD

**Issue by szczepanR** [robotframework/SwingLibrary#142]
there is no name property for a table that I need to click. I have only "com.emis.calui.Window_eventQueue$CalTable". Is there a possibility to detect that table?

**Comment by mihaiparvu** [comment]
In SwingLibrary it's possible to identify the table in two ways:
- `name` which is the preferred way - matches the internal name of the component (set using `setName` method in Java code)
- `index` which is a number, it is used as a zero-based index for the particular component type in the current context.

The detection by class name isn't implemented and does not make much sense because usually Java applications have multiple instances of the same class.

**Comment by szczepanR** [comment]
Sorry I meant object name. It is just an idea. Unfortunately, those two available methods don't work for me

**Comment by rticau** [comment]
@szczepanR can you give some more context, why the two options does not work for you?

**Comment by rticau** [comment]
No updates so closing this issue.
