### ISSUE TITLE
keyword passed but log shows exception

### ISSUE THREAD

**Issue by Bellama1** [robotframework/SwingLibrary#146]
Recently I run keyword: "push button" . Keyword is passed but button is not pushed and the log shows exception message. The reason is application has bug when push button and an exception is throw out. From my side, I want the keyword fails. How can I do?
![push button log](https://user-images.githubusercontent.com/39483613/110440904-22d9b280-80f4-11eb-9d17-e37763eded9d.jpg)

**Comment by mihaiparvu** [comment]
From SwingLibrary's perspective the button is pushed, so it doesn't make sense to FAIL the keyword just because there is a problem with the application under test. What you can try is to use one of the other keywords to verify if the event took place successfully by verifying how the app responded to the button push. 
e.g. after pushing the button, if a save dialog should appear, you should check that a dialog with specific title is visible, or the message save successful has appeared, etc. This of course depends on how the app was implemented.

Closing as this isn't a issue with SwingLibrary itself. For questions and support about the library you can post on robotframework support [forums ](https://forum.robotframework.org/c/libraries/swinglibrary/26)or [Slack channel](https://robotframework-slack-invite.herokuapp.com/).

**Comment by Bellama1** [comment]
Thanks for your reply. I will find another way to make it.
​​​​​​​
