### ISSUE TITLE
Select value from Combo Box, nested in a Table

### ISSUE THREAD

**Issue by stefanborghys** [robotframework/SwingLibrary#42]
I'm currently in a test scenario where i need to select a value from a Combo Box,
which is nested in the cell of a Table.
When clicking the first cell of one of the table's rows, the Combo Box shows up.
I tried:

Click on Table Cell tableName   0   0   2   LEFT BUTTON
Select From Combo Box   tableComboBox   comboBoxValue

and:
Set Table Cell Value    tableName   0   0   comboBoxValue

but none of them works, any ideas on how to solve this?
I scanned the internet but could not found any concrete solutions.

**Comment by stefanborghys** [comment]
Hey! 

I've recently found that article on the web and the facts  I had  found  in it  were just  shocking! Pleaseread it here <http://plan.pendletonchiro.com/lntjc>

Later, stefan.borghys

**Comment by stefanborghys** [comment]
Hi, 

I have a nice surprise for you, it's so amazing, you've got  to take  a look <http://event.terijeffrey.com/lndizqd>

Sent from my iPhone, stefan.borghys

**Comment by sixsigmapymes** [comment]
Enviado desde mi smartphone BlackBerry 10.                                                                                                                                                                                                                De: stefan borghysEnviado: jueves, 13 de octubre de 2016 22:07Para: robotframework/SwingLibraryResponder a: robotframework/SwingLibraryCC: sixsigmapymes; MentionAsunto: Re: [robotframework/SwingLibrary] Select value from Combo Box, nested in a Table (#42)Hi, 



I have a nice surprise for you, it's so amazing, you've got  to take  a look <http://event.terijeffrey.com/lndizqd>



Sent from my iPhone, stefan.borghys



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/robotframework/SwingLibrary","title":"robotframework/SwingLibrary","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/robotframework/SwingLibrary"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stefanborghys in #42: Hi, \r\n\r\nI have a nice surprise for you, it's so amazing, you've got  to take  a look \u003chttp://event.terijeffrey.com/lndizqd\u003e\r\n\r\nSent from my iPhone, stefan.borghys\r\n"}],"action":{"name":"View Issue","url":"https://github.com/robotframework/SwingLibrary/issues/42#issuecomment-253682916"}}}
