### ISSUE TITLE
Support for applets

### ISSUE THREAD

**Issue by tkp75** [robotframework/SwingLibrary#69]
Hello Experts,
I found <a href="https://code.google.com/p/robotframework-swinglibrary/issues/detail?id=189">issue 189: Enhance SwingLibrary to test applets</a> on google code, but could not map it into any issue on GitHub or on release notes. As that was accepted a long time ago, I was wondering if I missed something too obvious (like a separate library altogether).

Best regards,
   \- Tommi

**Comment by jussimalinen** [comment]
Well, I dont think SwingLibrary itself will ever support applets directly without the help of some other library. The problem here is that SwingLibrary needs to run in the same JVM so we need some way to communicate with Robot process and the JVM running the applet (unless you somehow manage to run robot in an applet, but I digress).

Unless someone from Nokia (the sponsor) requests this directly, I dont think we will have time to try to find a way to do this. As a workaround you could try testing a standalone version of the applet if possible?

**Comment by tkp75** [comment]
Thank You for the prompt answer,
As the future for Java applets looks bleak, I don't see applet support happening. So... I'll wrap an applet to start it as an application and hope it to be obsoleted sooner than later. This "feature request" ticket could be rejected as "not to be fixed" (for bookkeeping reasons).

**Comment by jussimalinen** [comment]
Cheers, hope the workaround works out for you.
